# Generated by Django 5.2.3 on 2025-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcheck', '0002_ipinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
